name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: .
    steps:
    - uses: actions/checkout@v3
    - name: 'Create env file'
      run: echo "${{ secrets.TWITTER_ENV_PRODUCTION }}" > .env.production
    - name: Build the Docker image
      run: docker build --progress=plain -t bndung/twitter:v2_prod -f Dockerfile .
      id: build
    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD}}
    - name: Push Docker image to Docker Hub
      run: docker push bndung/twitter:v2_prod
